export const GET_SEARCH_DATA_SUCCESS = 'GET_SEARCH_DATA_SUCCESS';
export const GET_SEARCH_DATA_ERROR = 'GET_SEARCH_DATA_ERROR';
export const SET_DATA_LOADING = 'SET_DATA_LOADING';
export const SET_COUNTER_VALUE = 'SET_COUNTER_VALUE';
